import type { NextPage } from "next";
import React, { useState, useRef, useEffect } from 'react';
import Head from "next/head";
import Image from "next/image";
import clsx from 'clsx';

const Home: NextPage = () => {
  const [messages, setMessages] = useState<string[]>([]);
  const [newMessage, setNewMessage] = useState('');
  const messagesContainerRef = useRef<HTMLDivElement>(null);

  useEffect(() => {
    setMessages(["Yinglong: I'm Yinglong, ask me something."]);
  }, []);

  useEffect(() => {
    if (messagesContainerRef.current) {
      messagesContainerRef.current.scrollTop =
        messagesContainerRef.current.scrollHeight;
    }
  }, [messages]);

  const handleSendQuery = async () => {
    if (newMessage.trim()) {
      setMessages((prevMessages) => [...prevMessages, `You: ${newMessage}`]);
      
      try{
        await fetch('http://127.0.0.1:8000/ai/openrouter/deepseek/post_query', {
          method: 'POST',
          headers: {
            'Content-Type': 'application/json',
          },
          body: JSON.stringify(
            {
              "messages": [
                  {"role": "system", "content": "You are a Chinese history expert"},
                  {"role": "user", "content": newMessage}
              ]
            }
          )
        }).then((response) => {
          if(!response.ok){
            return null;
          }
          
          return response.json();
        }).then((data) => {
          const YinglongsResponse = `YingLong: ${data}`;
          setMessages((prevMessages) => [...prevMessages, YinglongsResponse]);
        });
      } catch {
        console.log("Error");
      }
      setNewMessage('');
    }
  };

  const handleInputChange = (event: React.ChangeEvent<HTMLTextAreaElement>) => {
    setNewMessage(event.target.value);
  };

  const handleKeyDown = (event: React.KeyboardEvent<HTMLTextAreaElement>) => {
    if (event.key === 'Enter' && !event.shiftKey) {
      event.preventDefault(); 
      handleSendQuery();
    }
  };

  return (
    <>
      <Head>
        <title>Ancient Chinese History Assistant</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="flex flex-row">
        <div className="flex flex-col items-center justify-center w-1/3 min-h-screen mx-auto">
          <Image
            src="/dragon.png"
            height={250}
            width={250}
            alt="Image of scholarly dragon. AI Generated."
          />
          <h3 className="font-extrabold text-center text-10md">
            Ask me anything about ancient China
          </h3>
        </div>
        <div className="flex flex-col justify-center w-2/3 min-h-screen mx-auto">
        <div className="flex flex-col h-screen p-4">
            <div
              ref={messagesContainerRef}
              className="flex-grow mb-12 overflow-auto p-8 border border-solid border-[#ccc] rounded-sm"
            >
              {messages.map((message, index) => (
                <div
                  key={index}
                  className={clsx('p-2 rounded-sm mb-4 break-all', {
                    'bg-[#f9f9f9]': index % 2 == 0,
                    'bg-[#e9e9e9]': index % 2 != 0
                  },)}
                >
                  {message}
                </div>
              ))}
            </div>
            <div className="flex gap-4">
              <textarea
                id="userQuery"
                aria-label="userQuery"
                value={newMessage}
                onChange={handleInputChange}
                onKeyDown={handleKeyDown}
                placeholder="Hit me..."
                className="grow p-4 rounded-sm border border-solid border-[#ccc] resize-none"
                rows={3}
              />
              <button onClick={handleSendQuery} className="px-8 py-4 rounded-sm">
                Send
              </button>
            </div>
          </div>
        </div>
      </div>
    </>
  );
};

export default Home;
